# Copyright 2026 Private AI Ltd (SC881079)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""L3 contextual retrieval. Before embedding, prepend a
short LLM-generated line situating each chunk within its document. This is
pooling-agnostic — it changes the *text embedded*, not the pooling — so it is
fully compatible with Qwen3-Embedding's last-token pooling, unlike late
chunking. Generated by our own served LLM (zero-egress)."""

from __future__ import annotations

from . import llm
from .config import settings

_SYSTEM = (
    "You situate a chunk within its document to improve search retrieval. "
    "Given the document and one chunk from it, write ONE short sentence (max ~25 "
    "words) naming what the chunk is and where it sits — parties, section, dates, "
    "or topic — so the chunk is unambiguous on its own. Output only that sentence, "
    "no preamble."
)


def augment(blurb: str, chunk: str) -> str:
    """The text that gets embedded: the situating blurb, then the original chunk.
    The original is preserved verbatim so citations quote the source, not the blurb."""
    blurb = (blurb or "").strip()
    return f"{blurb}\n\n{chunk}" if blurb else chunk


async def contextualise(doc_text: str, chunk: str) -> str:
    """Return a 1–2 sentence situating blurb for `chunk` within `doc_text`.
    Best-effort: any failure yields an empty blurb (→ plain chunk via `augment`)."""
    try:
        user = (
            f"<document>\n{doc_text[: settings.contextual_doc_budget]}\n</document>\n\n"
            f"Chunk:\n{chunk}"
        )
        return (await llm.complete(_SYSTEM, user, max_tokens=80)).strip()
    except Exception:
        return ""
